package com.tyk.second.dao;

import org.springframework.stereotype.Repository;

@Repository
public class DemoImp  implements ReportDao{

	@Override
	public String findData() {
		System.out.println("Demo Implementation");
		return "Data Generated By DemoImp";
	}
	public DemoImp() {
		// TODO Auto-generated constructor stub
		System.out.println("DemoImp Constructor");
	}

}
